INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Advantage65 (Medicare Supplement)','Advantage65 (Medicare Supplement)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Advantage65 - Premier Select B& D (Mdcre Supplement)','Advantage65 - Premier Select B& D (Mdcre Supplement)')


INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Advantage65 - Select B& D (Mdcre Supplement)','Advantage65 - Select B& D (Mdcre Supplement)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Advantage65 - Select E (Mdcre Supplement)','Advantage65 - Select E (Mdcre Supplement)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueCare (HMO)','BlueCare (HMO)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueCare HMO with Dental and Vision','BlueCare HMO with Dental and Vision')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Bluecare HMO with Vision','Bluecare HMO with Vision')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueChoice','BlueChoice')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Choice PPO (Regional PPO)','BlueMedicare Choice PPO (Regional PPO)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Classic and Classic Plus HMO (My/Life Time)','BlueMedicare Classic and Classic Plus HMO (My/Life Time)')


INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Complete HMO','BlueMedicare Complete HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Group PPO','BlueMedicare Group PPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Premier HMO (Plus)','BlueMedicare Premier HMO (Plus)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Select PPO (Local PPO)','BlueMedicare Select PPO (Local PPO)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueMedicare Supplement Select (Medicare Supplement)','BlueMedicare Supplement Select (Medicare Supplement)')

INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueOptions','BlueOptions')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueOptions Health & Dental - Health','BlueOptions Health & Dental - Health')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueOptions Hospital Surgical Plus','BlueOptions Hospital Surgical Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueOptions with Dental and Vision','BlueOptions with Dental and Vision')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueOptions with Vision','BlueOptions with Vision')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueSelect','BlueSelect')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueSelect Hospital Surgical Plus','BlueSelect Hospital Surgical Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueSelect with Dental and Vision	','BlueSelect with Dental and Vision	')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'BlueSelect with Vision','BlueSelect with Vision')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Preferred Patient Care','Preferred Patient Care')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Temporary Insurance Protection','Temporary Insurance Protection')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Traditional','Traditional')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Florida Blue (Not marketplace)','Florida Blue (Not marketplace)')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Miami  Dade Blue','Miami  Dade Blue')



INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Charter EPO','Charter EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Charter HMO/HMO Plus','Charter HMO/HMO Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Charter POS','Charter POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Choice EPO','Choice EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Choice Plus HMO','Choice Plus HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Choice Plus POS','Choice Plus POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Compass EPO','Compass EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Compass Exclusion','Compass Exclusion')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Compass HMO/HMO Plus','Compass HMO/HMO Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Compass POS','Compass POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Core EPO','Core EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Core HMO','Core HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Navigate EPO','Navigate EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Navigate HMO/ HMO Plus','Navigate HMO/ HMO Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Navigate POS','Navigate POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO NR EPO','NexusACO NR EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO NR HMO','NexusACO NR HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO NR POS','NexusACO NR POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO OA POS','NexusACO OA POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO R EPO','NexusACO R EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO R HMO','NexusACO R HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO R POS','NexusACO R POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO OA EPO','NexusACO OA EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NexusACO OA HMO','NexusACO OA HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NHP Direct Access','NHP Direct Access')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NHP Gated','NHP Gated')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NHP Gated HMO','NHP Gated HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'NY Empire PPO','NY Empire PPO')

INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Select EPO','Select EPO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Select Plus HMO','Select Plus HMO')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Select Plus POS','Select Plus POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'UHC Core Choice Plus','UHC Core Choice Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Erickson Advantage','Erickson Advantage')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Evercare Plan DH','Evercare Plan DH')

INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Evercare Plan RDP','Evercare Plan RDP')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Evercare Plan IP','Evercare Plan IP')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Evercare Plan MH-POS','Evercare Plan MH-POS')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Evercare Advantage','Evercare Advantage')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'Medicare complete Choice Plan xx','Medicare complete Choice Plan xx')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'MedicareComplete Plus','MedicareComplete Plus')
INSERT INTO [dbo].[PlanTypes] ([PlanTypeId],[Code],[Name])VALUES(NEWID(),'MedicareComplete Choice Plan Essential','MedicareComplete Choice Plan Essential')


SELECT distinct Name  FROM [dbo].[PlanTypes]