// <auto-generated />
namespace CanoHealth.WebPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class OverrrideConventionsForCorporationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverrrideConventionsForCorporationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201802172115045_OverrrideConventionsForCorporationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
